default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  port: 3306
  database: wt_webtrees
  username: wt_user
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
