default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  port: 3306

development:
  <<: *default
  database: wt_webtrees
  username: photo_user
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: photoplace_test
  username: Eric
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  database: wt_webtrees
  username: photo_user
  host: <%= ENV['DB_URL'] %>
  port: <%= ENV['DB_PORT'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
