development:
  aws_id:               <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_cf_access_key_id: <%= ENV["AWS_CF_ACCESS_KEY_ID"] %>
  aws_cf_base_url:      <%= ENV["AWS_CF_BASE_URL"] %>
  aws_s3_base_dir:      <%= ENV["AWS_S3_BASE_DIR"] %>
  aws_s3_bucket:        <%= ENV["AWS_S3_BUCKET"] %>
  aws_secret:           <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  google_maps_key:      <%= ENV["GOOGLE_MAPS_KEY"] %>
  secret_key_base:      <%= ENV["SECRET_KEY_BASE"] %>

test:
  google_maps_key:      <%= ENV["GOOGLE_MAPS_KEY"] %>
  secret_key_base:      <%= ENV["SECRET_KEY_BASE"] %>

production:
  aws_id:               <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_cf_access_key_id: <%= ENV["AWS_CF_ACCESS_KEY_ID"] %>
  aws_cf_base_url:      <%= ENV["AWS_CF_BASE_URL"] %>
  aws_s3_base_dir:      <%= ENV["AWS_S3_BASE_DIR"] %>
  aws_s3_bucket:        <%= ENV["AWS_S3_BUCKET"] %>
  aws_secret:           <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  google_maps_key:      <%= ENV["GOOGLE_MAPS_KEY"] %>
  secret_key_base:      <%= ENV["SECRET_KEY_BASE"] %>
