development:
  google_maps_key: <%= ENV["GOOGLE_MAPS_KEY"] %>
  base_photo_path: <%= ENV["BASE_PHOTO_PATH"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  google_maps_key: <%= ENV["GOOGLE_MAPS_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  google_maps_key: <%= ENV["GOOGLE_MAPS_KEY"] %>
  base_photo_path: <%= ENV["BASE_PHOTO_PATH"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
